### ISSUE TITLE
[PALLET] Systemcraft

### ISSUE THREAD

**Issue by jam10o-new** [jam10o-new/pallets-unhinged#14]
* [ ] Rough Design/Description
* [ ] Implementation Braindump
* [ ] Informal Spec
* [ ] Tests-as-Spec
* [ ] Implementation
* [ ] Benchmarks
* [ ] WeightInfo
* [ ] Add Pallet to Meta Issue #1
