### ISSUE TITLE
[PALLET] Ratio

### ISSUE THREAD

**Issue by jam10o-new** [jam10o-new/pallets-unhinged#15]
WIP for [Datdot](https://datdot.org/) economic design.

* [x] Rough Design/Description
* [ ] Implementation Braindump
* [ ] Informal Spec
* [ ] Tests-as-Spec
* [ ] Implementation
* [ ] Benchmarks
* [ ] WeightInfo
* [ ] Add Pallet to Meta Issue #1
