### ISSUE TITLE
[PALLET] Samsara

### ISSUE THREAD

**Issue by jam10o-new** [jam10o-new/pallets-unhinged#4]
* [x] Rough Design/Description
* [ ] Implementation Braindump
* [ ] Informal Spec
* [ ] Tests-as-Spec
* [ ] Implementation
* [ ] Benchmarks
* [ ] WeightInfo
* [ ] Add Pallet to Meta Issue #1
